/**
 * Keyword dictionaries for thematic tag classification
 * Maps keywords found in scrutin titles to thematic domains
 */

export function getTagKeywords(tagSlug: string): string[] {
  const keywords: Record<string, string[]> = {
    "action-publique": [
      "fonction publique",
      "service public",
      "administration",
      "simplification",
      "décentralisation",
      "decentralisation",
      "collectivités",
      "collectivites",
      "territorial",
      "administration publique"
    ],
    agriculture: [
      "agriculture",
      "agriculteur",
      "agricole",
      "alimentation",
      "souveraineté alimentaire",
      "souverainete alimentaire",
      "rural",
      "ruralité",
      "ruralite",
      "exploitation agricole",
      "PAC",
      "politique agricole"
    ],
    amenagement: [
      "aménagement",
      "amenagement",
      "territoire",
      "urbanisme",
      "collectivités locales",
      "collectivites locales",
      "département",
      "departement",
      "région",
      "region",
      "commune",
      "intercommunalité",
      "intercommunalite"
    ],
    autonomie: [
      "handicap",
      "autonomie",
      "dépendance",
      "dependance",
      "accessibilité",
      "accessibilite",
      "personnes handicapées",
      "personnes handicapees",
      "AAH",
      "allocation"
    ],
    commerce: [
      "commerce",
      "artisanat",
      "PME",
      "petite entreprise",
      "moyenne entreprise",
      "TPE",
      "commerçant",
      "commercant",
      "artisan",
      "entrepreneur"
    ],
    culture: [
      "culture",
      "patrimoine",
      "art",
      "musée",
      "musee",
      "audiovisuel",
      "cinéma",
      "cinema",
      "spectacle",
      "livre",
      "édition",
      "edition",
      "média",
      "media"
    ],
    economie: [
      "économie",
      "economie",
      "finances",
      "budget",
      "fiscal",
      "fiscalité",
      "fiscalite",
      "impôt",
      "impot",
      "taxe",
      "industrie",
      "industriel",
      "souveraineté industrielle",
      "souverainete industrielle",
      "PIB",
      "croissance",
      "investissement"
    ],
    education: [
      "éducation",
      "education",
      "école",
      "ecole",
      "université",
      "universite",
      "enseignement",
      "recherche",
      "scientifique",
      "étudiant",
      "etudiant",
      "professeur",
      "formation",
      "lycée",
      "lycee",
      "collège",
      "college"
    ],
    europe: [
      "europe",
      "européen",
      "europeen",
      "UE",
      "Union européenne",
      "Union europeenne",
      "affaires étrangères",
      "affaires etrangeres",
      "diplomatie",
      "relations internationales",
      "étranger",
      "etranger",
      "international"
    ],
    interieur: [
      "sécurité",
      "securite",
      "police",
      "gendarmerie",
      "intérieur",
      "interieur",
      "ordre public",
      "sécurité publique",
      "securite publique",
      "défense",
      "defense",
      "terrorisme"
    ],
    justice: [
      "justice",
      "tribunal",
      "droit",
      "juridique",
      "pénal",
      "penal",
      "civile",
      "juridiction",
      "magistrat",
      "procureur",
      "avocat",
      "loi",
      "code"
    ],
    logement: [
      "logement",
      "habitat",
      "logement social",
      "HLM",
      "construction",
      "bâtiment",
      "batiment",
      "immobilier",
      "logement décent",
      "logement decent",
      "hébergement",
      "hebergement"
    ],
    sante: [
      "santé",
      "sante",
      "hôpital",
      "hopital",
      "médecin",
      "medecin",
      "soins",
      "médical",
      "medical",
      "santé publique",
      "sante publique",
      "médecine",
      "medecine",
      "pharmacie",
      "maladie",
      "santé mentale",
      "sante mentale"
    ],
    environnement: [
      "environnement",
      "écologie",
      "ecologie",
      "climat",
      "biodiversité",
      "biodiversite",
      "transition écologique",
      "transition ecologique",
      "transition énergétique",
      "transition energetique",
      "énergie",
      "energie",
      "hydroélectricité",
      "hydroelectricite",
      "hydroélectrique",
      "hydroelectrique",
      "renouvelable",
      "développement durable",
      "developpement durable",
      "pollution",
      "déchet",
      "dechet",
      "eau"
    ],
    transport: [
      "transport",
      "mobilité",
      "mobilite",
      "infrastructure",
      "route",
      "rail",
      "ferroviaire",
      "aérien",
      "aerien",
      "SNCF",
      "RATP",
      "métro",
      "metro",
      "véhicule",
      "vehicule",
      "automobile"
    ],
    travail: [
      "travail",
      "emploi",
      "chômage",
      "chomage",
      "salaire",
      "retraite",
      "formation professionnelle",
      "chômage",
      "chomage",
      "contrat",
      "CDI",
      "CDD",
      "sécurité sociale",
      "securite sociale",
      "assurance chômage",
      "assurance chomage"
    ]
  };

  return keywords[tagSlug] || [];
}

/**
 * Get all tag slugs
 */
export function getAllTagSlugs(): string[] {
  return [
    "action-publique",
    "agriculture",
    "amenagement",
    "autonomie",
    "commerce",
    "culture",
    "economie",
    "education",
    "europe",
    "interieur",
    "justice",
    "logement",
    "sante",
    "environnement",
    "transport",
    "travail"
  ];
}
